backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'content/portfolio'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Template', name: 'template', widget: 'select', options: [{label: 'Blog', value: 'blog'}, {label: 'Portfolio', value: 'portfolio'}], defualt: 'portfolio', hint: 'Select a page template' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home page'
        name: 'home'
        file: 'content/website-pages/home/index.md'
        editor:
          preview: false
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Welcome text', name: 'welcome', widget: 'markdown' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'About page'
        name: 'about'
        file: 'content/website-pages/about/index.md'
        editor:
          preview: false
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Contact page'
        name: 'contact'
        file: 'content/website-pages/contact/index.md'
        editor:
          preview: false
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Body', name: 'body', widget: 'markdown' }
